nginx:
  image: nginx
  links:
    - torrents 
    - plex
    - shows 
#  ports:
    #- 8081:80

plex:
  image: timhaak/plex
  volumes:
    - /srv/docker/vids/plex/config:/config
    - /srv/docker/vids/shows/downloads:/data
  ports:
    - 32400:32400

shows:
  image: timhaak/sickrage 
  links:
    - torrents 
  volumes:
    - /srv/docker/vids/torrents/downloads:/var/lib/transmission-daemon/downloads
    - /srv/docker/vids/shows/downloads:/downloads
    - /srv/docker/vids/shows/config:/config
    - /srv/docker/vids/shows/tv:/tv
    - /etc/localtime:/etc/localtime:ro
  ports:
    - 8081:8081

torrents:
   image: sutat/transmission
   volumes:
    - /srv/docker/vids/torrents/downloads:/var/lib/transmission-daemon/downloads
    - /srv/docker/vids/torrents/incomplete:/var/lib/transmission-daemon/incomplete
    - /srv/docker/vids/torrents/info:/var/lib/transmission-daemon/.config/transmission-daemon
    - /srv/docker/vids/shows/downloads:/downloads
   ports:
     - 9091
     - 51413:51413
     - 51413:51413/udp
